"""empty message

Revision ID: 3c6fc4a97dd4
Revises: 450d2b777164
Create Date: 2021-07-29 22:48:25.987640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6fc4a97dd4'
down_revision = '450d2b777164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    # ### end Alembic commands ###
