"""add email

Revision ID: 539bae324f45
Revises: 09a2e3648de7
Create Date: 2021-07-29 22:18:01.052361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539bae324f45'
down_revision = '09a2e3648de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
